# Generated by Django 5.0.6 on 2024-07-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codejam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonspace',
            name='category',
            field=models.CharField(default='area', max_length=150),
            preserve_default=False,
        ),
    ]
