# Generated by Django 5.0.6 on 2024-07-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codejam', '0002_commonspace_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commonspace',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codejam.category'),
        ),
    ]
